<Project Sdk="Uno.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PlayGuide.Core\PlayGuide.Core.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFrameworks>net9.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>PlayGuide</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.lkcode.playguide</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>O=Lars Kraemer</ApplicationPublisher>
    <!-- Package Description -->
    <Description>PlayGuide powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Hosting;
      Toolkit;
      Logging;
      LoggingSerilog;
      MVUX;
      Configuration;
      Localization;
      Navigation;
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

</Project>
